name: zack_shoping
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  video_player: ^2.9.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  scratcher: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #carousel_slider
    - lib/Asset/image/add1.jpg
    - lib/Asset/image/ADDD2.jpg
    - lib/Asset/image/ADDD3.jpg
    - lib/Asset/image/add4.jpg
    - lib/Asset/image/ADDD5.jpg
    - lib/Asset/image/ADDD6.jpg

    #logo
    - lib/Asset/image/zackwear.png

    #product
    - lib/Asset/image/product_img/product1.1.jpg
    - lib/Asset/image/product_img/product1.3.jpg
    - lib/Asset/image/product_img/product1.png
    - lib/Asset/image/product_img/product2.2.jpg
    - lib/Asset/image/product_img/product2.3.jpg
    - lib/Asset/image/product_img/product2.png
    - lib/Asset/image/product_img/product3.2.jpg
    - lib/Asset/image/product_img/product3.3.jpg
    - lib/Asset/image/product_img/product3.png
    - lib/Asset/image/product_img/product4.2.jpg
    - lib/Asset/image/product_img/product4.3.jpg
    - lib/Asset/image/product_img/product4.png
    - lib/Asset/image/product_img/product5.2.jpg
    - lib/Asset/image/product_img/product5.3.jpg
    - lib/Asset/image/product_img/product5.png
    - lib/Asset/image/product_img/product6.2.jpg
    - lib/Asset/image/product_img/product6.3.jpg
    - lib/Asset/image/product_img/product6.png
    - lib/Asset/image/product_img/product7.2.jpg
    - lib/Asset/image/product_img/product7.3.jpg
    - lib/Asset/image/product_img/product7.png
    - lib/Asset/image/product_img/product8.2.jpg
    - lib/Asset/image/product_img/product8.3.jpg
    - lib/Asset/image/product_img/product8.png
    - lib/Asset/image/product_img/product9.2.jpg
    - lib/Asset/image/product_img/product9.3.jpg
    - lib/Asset/image/product_img/product9.png
    - lib/Asset/image/product_img/product10.2.jpg
    - lib/Asset/image/product_img/product10.3.jpg
    - lib/Asset/image/product_img/product10.png
            #sporty images folder
    
    - lib/Asset/image/sporty_img/
    #notification
    - lib/Asset/image/notification/notification1.jpeg
    - lib/Asset/image/notification/notification2.jpeg
    - lib/Asset/image/notification/notification3.jpeg
    - lib/Asset/image/notification/scrach.jpeg
   

    #splash

    - lib/Asset/video/1730817185246958.mp4
    #add video
    - lib/Asset/video/af8b4c887b52afb86a9e5035f022a3de.mp4


    #loginpage
    - lib/Asset/image/login_image.png

    #cover images
    - lib/Asset/image/cover_image/sports.jpeg
    - lib/Asset/image/cover_image/casual.png
    - lib/Asset/image/cover_image/new.jpeg
    - lib/Asset/image/cover_image/denim.jpeg
    - lib/Asset/image/cover_image/shoes.jpeg


    #adds
    - lib/Asset/image/saleAdd.JPG
    - lib/Asset/image/Jewelryadd.png
    #profile
    - lib/Asset/image/shibili.jpeg
    



  fonts:
    - family: PoiretOne
      fonts:
        - asset: lib/Asset/fonts/PoiretOne-Regular.ttf
 