// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7w-BvXfU0ULnLbAjxQO12KQclIRqSQI',
    appId: '1:812809640156:web:3b1c99e5bd36557c5fbc19',
    messagingSenderId: '812809640156',
    projectId: 'zack-346df',
    authDomain: 'zack-346df.firebaseapp.com',
    storageBucket: 'zack-346df.appspot.com',
    measurementId: 'G-4BRL16YZC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM-9hq0fFBGx42OsmwqAdJ_G3j_AHR-GU',
    appId: '1:812809640156:android:fe141e2a322d70a85fbc19',
    messagingSenderId: '812809640156',
    projectId: 'zack-346df',
    storageBucket: 'zack-346df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwVb6VhmX_PsXnxUE5gd4dYjJVSCQ2LM',
    appId: '1:812809640156:ios:d7a54b29152286a35fbc19',
    messagingSenderId: '812809640156',
    projectId: 'zack-346df',
    storageBucket: 'zack-346df.appspot.com',
    iosBundleId: 'com.example.zackShoping',
  );
}
